import { Subject } from './types';

export const SUBJECTS: Subject[] = [
  {
    id: 'mathematics',
    name: 'Mathematics',
    nameSi: 'ගණිතය',
    icon: 'Calculator',
    color: 'bg-blue-500',
  },
  {
    id: 'science',
    name: 'Science',
    nameSi: 'විද්‍යාව',
    icon: 'Beaker',
    color: 'bg-green-500',
  },
  {
    id: 'sinhala',
    name: 'Sinhala',
    nameSi: 'සිංහල',
    icon: 'Languages',
    color: 'bg-orange-500',
  },
  {
    id: 'english',
    name: 'English',
    nameSi: 'ඉංග්‍රීසි',
    icon: 'Type',
    color: 'bg-purple-500',
  },
  {
    id: 'history',
    name: 'History',
    nameSi: 'ඉතිහාසය',
    icon: 'History',
    color: 'bg-red-500',
  },
  {
    id: 'buddhism',
    name: 'Buddhism',
    nameSi: 'බුද්ධ ධර්මය',
    icon: 'DharmaWheel',
    color: 'bg-yellow-500',
  },
  {
    id: 'commercial',
    name: 'Business & Accounting',
    nameSi: 'ව්‍යාපාර හා ගිණුම්කරණ අධ්‍යයනය',
    icon: 'Briefcase',
    color: 'bg-indigo-500',
  },
  {
    id: 'ict',
    name: 'ICT',
    nameSi: 'තොරතුරු හා සන්නිවේදන තාක්ෂණය',
    icon: 'Monitor',
    color: 'bg-cyan-500',
  },
  {
    id: 'geography',
    name: 'Geography',
    nameSi: 'භූගෝල විද්‍යාව',
    icon: 'Globe',
    color: 'bg-emerald-500',
  },
  {
    id: 'citizenship',
    name: 'Citizenship Education',
    nameSi: 'පුරවැසි අධ්‍යාපනය',
    icon: 'ShieldCheck',
    color: 'bg-sky-500',
  },
  {
    id: 'entrepreneurship',
    name: 'Entrepreneurship Studies',
    nameSi: 'ව්‍යවසායකත්ව අධ්‍යයනය',
    icon: 'Coins',
    color: 'bg-pink-500',
  },
  {
    id: 'art',
    name: 'Art',
    nameSi: 'චිත්‍ර කලාව',
    icon: 'Palette',
    color: 'bg-rose-500',
  },
  {
    id: 'music',
    name: 'Music',
    nameSi: 'සංගීතය',
    icon: 'Music',
    color: 'bg-violet-500',
  },
  {
    id: 'dancing',
    name: 'Dancing',
    nameSi: 'නර්තනය',
    icon: 'Activity',
    color: 'bg-fuchsia-500',
  },
  {
    id: 'drama',
    name: 'Drama & Theatre',
    nameSi: 'නාට්‍ය හා රංග කලාව',
    icon: 'Theater',
    color: 'bg-purple-600',
  },
  {
    id: 'health',
    name: 'Health & Physical Ed.',
    nameSi: 'සෞඛ්‍ය හා ශාරීරික අධ්‍යාපනය',
    icon: 'HeartPulse',
    color: 'bg-teal-500',
  },
  {
    id: 'media',
    name: 'Communication & Media',
    nameSi: 'සන්නිවේදනය හා මාධ්‍ය අධ්‍යයනය',
    icon: 'Radio',
    color: 'bg-blue-600',
  },
  {
    id: 'agriculture',
    name: 'Agriculture & Food Tech',
    nameSi: 'කෘෂිකර්මය හා ආහාර තාක්ෂණය',
    icon: 'Sprout',
    color: 'bg-amber-600',
  },
  {
    id: 'home_economics',
    name: 'Home Economics',
    nameSi: 'ගෘහ ආර්ථික විද්‍යාව',
    icon: 'Home',
    color: 'bg-orange-600',
  },
  {
    id: 'tamil',
    name: 'Tamil Language',
    nameSi: 'දෙමළ භාෂාව',
    icon: 'Languages',
    color: 'bg-lime-600',
  },
  {
    id: 'literature',
    name: 'Literature',
    nameSi: 'සාහිත්‍යය අධ්‍යයනය',
    icon: 'BookOpen',
    color: 'bg-yellow-600',
  },
];
